[2023-11-07 21:34:58,054] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:34:57.199753+00:00 [queued]>
[2023-11-07 21:34:58,065] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:34:57.199753+00:00 [queued]>
[2023-11-07 21:34:58,065] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:34:58,065] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 21:34:58,065] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:34:58,080] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 21:34:57.199753+00:00
[2023-11-07 21:34:58,088] {standard_task_runner.py:52} INFO - Started process 1729 to run task
[2023-11-07 21:34:58,093] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag', 'test_selenium', 'manual__2023-11-07T21:34:57.199753+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmpo8r1x0lj', '--error-file', '/tmp/tmpti07a2ng']
[2023-11-07 21:34:58,096] {standard_task_runner.py:80} INFO - Job 34: Subtask test_selenium
[2023-11-07 21:34:58,187] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:34:57.199753+00:00 [running]> on host ad682aabf7c8
[2023-11-07 21:34:58,293] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T21:34:57.199753+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T21:34:57.199753+00:00
[2023-11-07 21:34:58,294] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 21:34:58,556] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:34:58,615] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:34:58,659] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 21:35:07,165] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 32, in test_selenium_driver
    username_input.send_keys(username)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 230, in send_keys
    self._execute(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=119.0.6045.105)
Stacktrace:
#0 0x55cc1d4785e3 <unknown>
#1 0x55cc1d13af0d <unknown>
#2 0x55cc1d18296f <unknown>
#3 0x55cc1d180d62 <unknown>
#4 0x55cc1d1afef2 <unknown>
#5 0x55cc1d17ca02 <unknown>
#6 0x55cc1d1b00be <unknown>
#7 0x55cc1d1cbb3d <unknown>
#8 0x55cc1d1afcc3 <unknown>
#9 0x55cc1d17b0e4 <unknown>
#10 0x55cc1d17c0ae <unknown>
#11 0x55cc1d43ece1 <unknown>
#12 0x55cc1d442b7e <unknown>
#13 0x55cc1d42c4b5 <unknown>
#14 0x55cc1d4437d6 <unknown>
#15 0x55cc1d40fdbf <unknown>
#16 0x55cc1d466748 <unknown>
#17 0x55cc1d466917 <unknown>
#18 0x55cc1d477773 <unknown>
#19 0x7f1bc6e99ea7 start_thread

[2023-11-07 21:35:07,186] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_dag, task_id=test_selenium, execution_date=20231107T213457, start_date=20231107T213458, end_date=20231107T213507
[2023-11-07 21:35:07,204] {standard_task_runner.py:92} ERROR - Failed to execute job 34 for task test_selenium (Message: element not interactable
  (Session info: chrome=119.0.6045.105)
Stacktrace:
#0 0x55cc1d4785e3 <unknown>
#1 0x55cc1d13af0d <unknown>
#2 0x55cc1d18296f <unknown>
#3 0x55cc1d180d62 <unknown>
#4 0x55cc1d1afef2 <unknown>
#5 0x55cc1d17ca02 <unknown>
#6 0x55cc1d1b00be <unknown>
#7 0x55cc1d1cbb3d <unknown>
#8 0x55cc1d1afcc3 <unknown>
#9 0x55cc1d17b0e4 <unknown>
#10 0x55cc1d17c0ae <unknown>
#11 0x55cc1d43ece1 <unknown>
#12 0x55cc1d442b7e <unknown>
#13 0x55cc1d42c4b5 <unknown>
#14 0x55cc1d4437d6 <unknown>
#15 0x55cc1d40fdbf <unknown>
#16 0x55cc1d466748 <unknown>
#17 0x55cc1d466917 <unknown>
#18 0x55cc1d477773 <unknown>
#19 0x7f1bc6e99ea7 start_thread
; 1729)
[2023-11-07 21:35:07,226] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 21:35:07,278] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
