[2023-11-07T15:59:35.796+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract.load_parquet manual__2023-11-07T15:59:32.731821+00:00 [queued]>
[2023-11-07T15:59:35.807+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract.load_parquet manual__2023-11-07T15:59:32.731821+00:00 [queued]>
[2023-11-07T15:59:35.808+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-07T15:59:35.825+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryInsertJobOperator): load_parquet> on 2023-11-07 15:59:32.731821+00:00
[2023-11-07T15:59:35.834+0000] {standard_task_runner.py:57} INFO - Started process 365 to run task
[2023-11-07T15:59:35.841+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract', 'load_parquet', 'manual__2023-11-07T15:59:32.731821+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmpvgihrrho']
[2023-11-07T15:59:35.845+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask load_parquet
[2023-11-07T15:59:35.939+0000] {task_command.py:416} INFO - Running <TaskInstance: extract.load_parquet manual__2023-11-07T15:59:32.731821+00:00 [running]> on host 48017e158481
[2023-11-07T15:59:36.082+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract' AIRFLOW_CTX_TASK_ID='load_parquet' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T15:59:32.731821+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T15:59:32.731821+00:00'
[2023-11-07T15:59:36.120+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2786, in execute
    hook = BigQueryHook(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 118, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 242, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2023-11-07T15:59:36.126+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=extract, task_id=load_parquet, execution_date=20231107T155932, start_date=20231107T155935, end_date=20231107T155936
[2023-11-07T15:59:36.147+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task load_parquet (The conn_id `google_cloud_default` isn't defined; 365)
[2023-11-07T15:59:36.176+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T15:59:36.204+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
