[2023-11-07 09:56:29,522] {processor.py:153} INFO - Started process (PID=157) to work on /app/airflow/dags/advanced/dbt_advanced.py
[2023-11-07 09:56:29,523] {processor.py:641} INFO - Processing file /app/airflow/dags/advanced/dbt_advanced.py for tasks to queue
[2023-11-07 09:56:29,524] {logging_mixin.py:115} INFO - [2023-11-07 09:56:29,523] {dagbag.py:507} INFO - Filling up the DagBag from /app/airflow/dags/advanced/dbt_advanced.py
[2023-11-07 09:56:29,543] {logging_mixin.py:115} INFO - [2023-11-07 09:56:29,542] {dagbag.py:320} ERROR - Failed to import: /app/airflow/dags/advanced/dbt_advanced.py
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/advanced/dbt_advanced.py", line 99, in <module>
    with open(f"{DBT_DIR}/manifest.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/airflow/dbt_lewagon/manifest.json'
[2023-11-07 09:56:29,543] {processor.py:653} WARNING - No viable dags retrieved from /app/airflow/dags/advanced/dbt_advanced.py
[2023-11-07 09:56:29,587] {processor.py:161} INFO - Processing /app/airflow/dags/advanced/dbt_advanced.py took 0.073 seconds
[2023-11-07 09:56:59,695] {processor.py:153} INFO - Started process (PID=168) to work on /app/airflow/dags/advanced/dbt_advanced.py
[2023-11-07 09:56:59,699] {processor.py:641} INFO - Processing file /app/airflow/dags/advanced/dbt_advanced.py for tasks to queue
[2023-11-07 09:56:59,700] {logging_mixin.py:115} INFO - [2023-11-07 09:56:59,700] {dagbag.py:507} INFO - Filling up the DagBag from /app/airflow/dags/advanced/dbt_advanced.py
[2023-11-07 09:56:59,709] {logging_mixin.py:115} INFO - [2023-11-07 09:56:59,708] {dagbag.py:320} ERROR - Failed to import: /app/airflow/dags/advanced/dbt_advanced.py
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/advanced/dbt_advanced.py", line 99, in <module>
    with open(f"{DBT_DIR}/manifest.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/airflow/dbt_lewagon/manifest.json'
[2023-11-07 09:56:59,710] {processor.py:653} WARNING - No viable dags retrieved from /app/airflow/dags/advanced/dbt_advanced.py
[2023-11-07 09:56:59,740] {processor.py:161} INFO - Processing /app/airflow/dags/advanced/dbt_advanced.py took 0.050 seconds
[2023-11-07 09:57:29,859] {processor.py:153} INFO - Started process (PID=178) to work on /app/airflow/dags/advanced/dbt_advanced.py
[2023-11-07 09:57:29,864] {processor.py:641} INFO - Processing file /app/airflow/dags/advanced/dbt_advanced.py for tasks to queue
[2023-11-07 09:57:29,865] {logging_mixin.py:115} INFO - [2023-11-07 09:57:29,865] {dagbag.py:507} INFO - Filling up the DagBag from /app/airflow/dags/advanced/dbt_advanced.py
[2023-11-07 09:57:29,877] {logging_mixin.py:115} INFO - [2023-11-07 09:57:29,876] {dagbag.py:320} ERROR - Failed to import: /app/airflow/dags/advanced/dbt_advanced.py
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/airflow/dags/advanced/dbt_advanced.py", line 99, in <module>
    with open(f"{DBT_DIR}/manifest.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/airflow/dbt_lewagon/manifest.json'
[2023-11-07 09:57:29,877] {processor.py:653} WARNING - No viable dags retrieved from /app/airflow/dags/advanced/dbt_advanced.py
[2023-11-07 09:57:29,942] {processor.py:161} INFO - Processing /app/airflow/dags/advanced/dbt_advanced.py took 0.089 seconds
