[2023-11-07 21:29:04,486] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:29:04.029605+00:00 [queued]>
[2023-11-07 21:29:04,498] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:29:04.029605+00:00 [queued]>
[2023-11-07 21:29:04,499] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:29:04,499] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 21:29:04,499] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:29:04,515] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 21:29:04.029605+00:00
[2023-11-07 21:29:04,522] {standard_task_runner.py:52} INFO - Started process 848 to run task
[2023-11-07 21:29:04,531] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag', 'test_selenium', 'manual__2023-11-07T21:29:04.029605+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmpujzfw6dd', '--error-file', '/tmp/tmpftmomw0o']
[2023-11-07 21:29:04,536] {standard_task_runner.py:80} INFO - Job 31: Subtask test_selenium
[2023-11-07 21:29:04,650] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:29:04.029605+00:00 [running]> on host ad682aabf7c8
[2023-11-07 21:29:04,777] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T21:29:04.029605+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T21:29:04.029605+00:00
[2023-11-07 21:29:04,779] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 21:29:05,149] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:29:05,206] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:29:05,243] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 21:29:38,983] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 57, in test_selenium_driver
    csv_button = WebDriverWait(driver, 10).until(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 101, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

[2023-11-07 21:29:39,006] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_dag, task_id=test_selenium, execution_date=20231107T212904, start_date=20231107T212904, end_date=20231107T212939
[2023-11-07 21:29:39,024] {standard_task_runner.py:92} ERROR - Failed to execute job 31 for task test_selenium (Message: 
; 848)
[2023-11-07 21:29:39,075] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 21:29:39,124] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
