[2023-11-08T08:03:00.603+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T08:03:00.618+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T08:03:00.618+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 5
[2023-11-08T08:03:00.634+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2023-11-07 00:00:00+00:00
[2023-11-08T08:03:00.643+0000] {standard_task_runner.py:57} INFO - Started process 306 to run task
[2023-11-08T08:03:00.651+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract', 'dbt_run', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmpx86w_k5f']
[2023-11-08T08:03:00.655+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask dbt_run
[2023-11-08T08:03:00.749+0000] {task_command.py:416} INFO - Running <TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [running]> on host e37a8383d3d6
[2023-11-08T08:03:00.880+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-08T08:03:00.886+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T08:03:00.887+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --project-dir /app/airflow/dbt_nba']
[2023-11-08T08:03:00.906+0000] {subprocess.py:86} INFO - Output:
[2023-11-08T08:03:05.450+0000] {subprocess.py:93} INFO - [0m08:03:05  Running with dbt=1.7.0
[2023-11-08T08:03:07.139+0000] {subprocess.py:93} INFO - [0m08:03:07  Registered adapter: bigquery=1.7.0
[2023-11-08T08:03:07.155+0000] {subprocess.py:93} INFO - [0m08:03:07  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2023-11-08T08:03:08.800+0000] {subprocess.py:93} INFO - [0m08:03:08  [[33mWARNING[0m]: Did not find matching node for patch with name 'my_first_dbt_model' in the 'models' section of file 'models/example/schema.yml'
[2023-11-08T08:03:08.996+0000] {subprocess.py:93} INFO - [0m08:03:08  [[33mWARNING[0m]: Test 'test.nba_stats.unique_my_first_dbt_model_id.16e066b321' (models/example/schema.yml) depends on a node named 'my_first_dbt_model' in package '' which was not found
[2023-11-08T08:03:08.997+0000] {subprocess.py:93} INFO - [0m08:03:08  [[33mWARNING[0m]: Test 'test.nba_stats.not_null_my_first_dbt_model_id.5fb22c2710' (models/example/schema.yml) depends on a node named 'my_first_dbt_model' in package '' which was not found
[2023-11-08T08:03:09.083+0000] {subprocess.py:93} INFO - [0m08:03:09  Found 2 models, 2 tests, 0 sources, 0 exposures, 0 metrics, 447 macros, 0 groups, 0 semantic models
[2023-11-08T08:03:09.087+0000] {subprocess.py:93} INFO - [0m08:03:09
[2023-11-08T08:03:09.097+0000] {subprocess.py:93} INFO - [0m08:03:09
[2023-11-08T08:03:09.098+0000] {subprocess.py:93} INFO - [0m08:03:09  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2023-11-08T08:03:09.099+0000] {subprocess.py:93} INFO - [0m08:03:09  Encountered an error:
[2023-11-08T08:03:09.100+0000] {subprocess.py:93} INFO - Database Error
[2023-11-08T08:03:09.100+0000] {subprocess.py:93} INFO -   [Errno 2] No such file or directory: '/home/marius.fall/code/.gcp_keys/dbt_lewagon/le-wagon-de-bootcamp.json'
[2023-11-08T08:03:10.084+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-08T08:03:10.106+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-08T08:03:10.112+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=extract, task_id=dbt_run, execution_date=20231107T000000, start_date=20231108T080300, end_date=20231108T080310
[2023-11-08T08:03:10.134+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 306)
[2023-11-08T08:03:10.180+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T08:03:10.245+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
