[2023-11-08T07:55:13.598+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:55:13.618+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:55:13.619+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-11-08T07:55:13.645+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2023-11-07 00:00:00+00:00
[2023-11-08T07:55:13.658+0000] {standard_task_runner.py:57} INFO - Started process 185 to run task
[2023-11-08T07:55:13.669+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract', 'dbt_run', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmpxq701vra']
[2023-11-08T07:55:13.673+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask dbt_run
[2023-11-08T07:55:13.762+0000] {task_command.py:416} INFO - Running <TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [running]> on host e37a8383d3d6
[2023-11-08T07:55:13.887+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-08T07:55:13.891+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T07:55:13.892+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --project-dir /app/airflow/dbt_nba']
[2023-11-08T07:55:13.911+0000] {subprocess.py:86} INFO - Output:
[2023-11-08T07:55:18.588+0000] {subprocess.py:93} INFO - [0m07:55:18  Running with dbt=1.7.0
[2023-11-08T07:55:18.594+0000] {subprocess.py:93} INFO - [0m07:55:18  Encountered an error:
[2023-11-08T07:55:18.595+0000] {subprocess.py:93} INFO - Runtime Error
[2023-11-08T07:55:18.596+0000] {subprocess.py:93} INFO -   Could not find profile named 'nba_stats'
[2023-11-08T07:55:19.322+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-08T07:55:19.343+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-08T07:55:19.349+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=extract, task_id=dbt_run, execution_date=20231107T000000, start_date=20231108T075513, end_date=20231108T075519
[2023-11-08T07:55:19.369+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 185)
[2023-11-08T07:55:19.393+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T07:55:19.419+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
