[2023-11-07T17:35:29.366+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract.dbt_run manual__2023-11-07T17:32:08.537403+00:00 [queued]>
[2023-11-07T17:35:29.379+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract.dbt_run manual__2023-11-07T17:32:08.537403+00:00 [queued]>
[2023-11-07T17:35:29.379+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-07T17:35:29.396+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2023-11-07 17:32:08.537403+00:00
[2023-11-07T17:35:29.405+0000] {standard_task_runner.py:57} INFO - Started process 214 to run task
[2023-11-07T17:35:29.412+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract', 'dbt_run', 'manual__2023-11-07T17:32:08.537403+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmpjl3qmqsh']
[2023-11-07T17:35:29.417+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask dbt_run
[2023-11-07T17:35:29.504+0000] {task_command.py:416} INFO - Running <TaskInstance: extract.dbt_run manual__2023-11-07T17:32:08.537403+00:00 [running]> on host 48017e158481
[2023-11-07T17:35:29.639+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T17:32:08.537403+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T17:32:08.537403+00:00'
[2023-11-07T17:35:29.643+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-07T17:35:29.649+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --models first_model --project-dir /app/airflow/dbt_lewagon']
[2023-11-07T17:35:29.677+0000] {subprocess.py:86} INFO - Output:
[2023-11-07T17:35:35.759+0000] {subprocess.py:93} INFO - [0m17:35:35  Running with dbt=1.7.0
[2023-11-07T17:35:35.761+0000] {subprocess.py:93} INFO - [0m17:35:35  Encountered an error:
[2023-11-07T17:35:35.762+0000] {subprocess.py:93} INFO - Runtime Error
[2023-11-07T17:35:35.763+0000] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /app/airflow/dbt_lewagon/dbt_project.yml
[2023-11-07T17:35:35.763+0000] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2023-11-07T17:35:35.763+0000] {subprocess.py:93} INFO - 
[2023-11-07T17:35:36.463+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-07T17:35:36.485+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-07T17:35:36.491+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=extract, task_id=dbt_run, execution_date=20231107T173208, start_date=20231107T173529, end_date=20231107T173536
[2023-11-07T17:35:36.513+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 214)
[2023-11-07T17:35:36.547+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T17:35:36.578+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
