[2023-11-07 21:51:32,167] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag_data.test_selenium manual__2023-11-07T21:51:31.517679+00:00 [queued]>
[2023-11-07 21:51:32,179] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag_data.test_selenium manual__2023-11-07T21:51:31.517679+00:00 [queued]>
[2023-11-07 21:51:32,179] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:51:32,179] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 21:51:32,179] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:51:32,194] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 21:51:31.517679+00:00
[2023-11-07 21:51:32,199] {standard_task_runner.py:52} INFO - Started process 4174 to run task
[2023-11-07 21:51:32,204] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag_data', 'test_selenium', 'manual__2023-11-07T21:51:31.517679+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmp3mul5mv4', '--error-file', '/tmp/tmpcddptaun']
[2023-11-07 21:51:32,207] {standard_task_runner.py:80} INFO - Job 41: Subtask test_selenium
[2023-11-07 21:51:32,306] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag_data.test_selenium manual__2023-11-07T21:51:31.517679+00:00 [running]> on host ad682aabf7c8
[2023-11-07 21:51:32,413] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag_data
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T21:51:31.517679+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T21:51:31.517679+00:00
[2023-11-07 21:51:32,415] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 21:51:32,704] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:51:32,757] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:51:32,793] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 21:52:01,831] {logging_mixin.py:115} INFO - Logged in
[2023-11-07 21:52:07,136] {logging_mixin.py:115} INFO - Hovered over export data
[2023-11-07 21:52:08,241] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 62, in test_selenium_driver
    csv_button.click()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (109, 482)
  (Session info: chrome=119.0.6045.105)
Stacktrace:
#0 0x55aa7c91ece3 <unknown>
#1 0x55aa7c5eca3e <unknown>
#2 0x55aa7c63da1b <unknown>
#3 0x55aa7c63b616 <unknown>
#4 0x55aa7c638da0 <unknown>
#5 0x55aa7c638074 <unknown>
#6 0x55aa7c62af1a <unknown>
#7 0x55aa7c65ec92 <unknown>
#8 0x55aa7c62a788 <unknown>
#9 0x55aa7c65ee1e <unknown>
#10 0x55aa7c677288 <unknown>
#11 0x55aa7c65ea43 <unknown>
#12 0x55aa7c628bc6 <unknown>
#13 0x55aa7c629fb2 <unknown>
#14 0x55aa7c8f3d67 <unknown>
#15 0x55aa7c8f6e4d <unknown>
#16 0x55aa7c8f68f8 <unknown>
#17 0x55aa7c8f7365 <unknown>
#18 0x55aa7c8e619f <unknown>
#19 0x55aa7c8f76f2 <unknown>
#20 0x55aa7c8d0626 <unknown>
#21 0x55aa7c90fe55 <unknown>
#22 0x55aa7c91003b <unknown>
#23 0x55aa7c91e26f <unknown>
#24 0x7f24d1dc8ea7 start_thread

[2023-11-07 21:52:08,261] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_dag_data, task_id=test_selenium, execution_date=20231107T215131, start_date=20231107T215132, end_date=20231107T215208
[2023-11-07 21:52:08,278] {standard_task_runner.py:92} ERROR - Failed to execute job 41 for task test_selenium (Message: element click intercepted: Element is not clickable at point (109, 482)
  (Session info: chrome=119.0.6045.105)
Stacktrace:
#0 0x55aa7c91ece3 <unknown>
#1 0x55aa7c5eca3e <unknown>
#2 0x55aa7c63da1b <unknown>
#3 0x55aa7c63b616 <unknown>
#4 0x55aa7c638da0 <unknown>
#5 0x55aa7c638074 <unknown>
#6 0x55aa7c62af1a <unknown>
#7 0x55aa7c65ec92 <unknown>
#8 0x55aa7c62a788 <unknown>
#9 0x55aa7c65ee1e <unknown>
#10 0x55aa7c677288 <unknown>
#11 0x55aa7c65ea43 <unknown>
#12 0x55aa7c628bc6 <unknown>
#13 0x55aa7c629fb2 <unknown>
#14 0x55aa7c8f3d67 <unknown>
#15 0x55aa7c8f6e4d <unknown>
#16 0x55aa7c8f68f8 <unknown>
#17 0x55aa7c8f7365 <unknown>
#18 0x55aa7c8e619f <unknown>
#19 0x55aa7c8f76f2 <unknown>
#20 0x55aa7c8d0626 <unknown>
#21 0x55aa7c90fe55 <unknown>
#22 0x55aa7c91003b <unknown>
#23 0x55aa7c91e26f <unknown>
#24 0x7f24d1dc8ea7 start_thread
; 4174)
[2023-11-07 21:52:08,314] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 21:52:08,356] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
