[2023-11-07 21:41:42,654] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag_data.test_selenium manual__2023-11-07T21:41:42.101681+00:00 [queued]>
[2023-11-07 21:41:42,666] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag_data.test_selenium manual__2023-11-07T21:41:42.101681+00:00 [queued]>
[2023-11-07 21:41:42,666] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:41:42,666] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 21:41:42,667] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:41:42,683] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 21:41:42.101681+00:00
[2023-11-07 21:41:42,689] {standard_task_runner.py:52} INFO - Started process 2811 to run task
[2023-11-07 21:41:42,696] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag_data', 'test_selenium', 'manual__2023-11-07T21:41:42.101681+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmpc421bghq', '--error-file', '/tmp/tmpksd7s13q']
[2023-11-07 21:41:42,700] {standard_task_runner.py:80} INFO - Job 37: Subtask test_selenium
[2023-11-07 21:41:42,792] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag_data.test_selenium manual__2023-11-07T21:41:42.101681+00:00 [running]> on host ad682aabf7c8
[2023-11-07 21:41:42,905] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag_data
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T21:41:42.101681+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T21:41:42.101681+00:00
[2023-11-07 21:41:42,906] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 21:41:43,205] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:41:43,268] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:41:43,307] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 21:42:14,023] {logging_mixin.py:115} INFO - Logged in
[2023-11-07 21:42:29,441] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 60, in test_selenium_driver
    csv_button = WebDriverWait(driver, 10).until(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 101, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

[2023-11-07 21:42:29,463] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_dag_data, task_id=test_selenium, execution_date=20231107T214142, start_date=20231107T214142, end_date=20231107T214229
[2023-11-07 21:42:29,481] {standard_task_runner.py:92} ERROR - Failed to execute job 37 for task test_selenium (Message: 
; 2811)
[2023-11-07 21:42:29,531] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 21:42:29,583] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
