[2023-11-07 21:35:50,686] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:35:49.370330+00:00 [queued]>
[2023-11-07 21:35:50,699] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:35:49.370330+00:00 [queued]>
[2023-11-07 21:35:50,700] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:35:50,701] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 21:35:50,701] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:35:50,718] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 21:35:49.370330+00:00
[2023-11-07 21:35:50,728] {standard_task_runner.py:52} INFO - Started process 2014 to run task
[2023-11-07 21:35:50,744] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag', 'test_selenium', 'manual__2023-11-07T21:35:49.370330+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmpxwmh549e', '--error-file', '/tmp/tmpul_rfgwa']
[2023-11-07 21:35:50,748] {standard_task_runner.py:80} INFO - Job 35: Subtask test_selenium
[2023-11-07 21:35:50,852] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag.test_selenium manual__2023-11-07T21:35:49.370330+00:00 [running]> on host ad682aabf7c8
[2023-11-07 21:35:50,958] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T21:35:49.370330+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T21:35:49.370330+00:00
[2023-11-07 21:35:50,959] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 21:35:51,263] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:35:51,323] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:35:51,388] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 21:35:59,980] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 31, in test_selenium_driver
    username_input.send_keys(username)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 230, in send_keys
    self._execute(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=119.0.6045.105)
Stacktrace:
#0 0x557b4bdae5e3 <unknown>
#1 0x557b4ba70f0d <unknown>
#2 0x557b4bab896f <unknown>
#3 0x557b4bab6d62 <unknown>
#4 0x557b4bae5ef2 <unknown>
#5 0x557b4bab2a02 <unknown>
#6 0x557b4bae60be <unknown>
#7 0x557b4bb01b3d <unknown>
#8 0x557b4bae5cc3 <unknown>
#9 0x557b4bab10e4 <unknown>
#10 0x557b4bab20ae <unknown>
#11 0x557b4bd74ce1 <unknown>
#12 0x557b4bd78b7e <unknown>
#13 0x557b4bd624b5 <unknown>
#14 0x557b4bd797d6 <unknown>
#15 0x557b4bd45dbf <unknown>
#16 0x557b4bd9c748 <unknown>
#17 0x557b4bd9c917 <unknown>
#18 0x557b4bdad773 <unknown>
#19 0x7fab6a7abea7 start_thread

[2023-11-07 21:36:00,024] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_dag, task_id=test_selenium, execution_date=20231107T213549, start_date=20231107T213550, end_date=20231107T213600
[2023-11-07 21:36:00,060] {standard_task_runner.py:92} ERROR - Failed to execute job 35 for task test_selenium (Message: element not interactable
  (Session info: chrome=119.0.6045.105)
Stacktrace:
#0 0x557b4bdae5e3 <unknown>
#1 0x557b4ba70f0d <unknown>
#2 0x557b4bab896f <unknown>
#3 0x557b4bab6d62 <unknown>
#4 0x557b4bae5ef2 <unknown>
#5 0x557b4bab2a02 <unknown>
#6 0x557b4bae60be <unknown>
#7 0x557b4bb01b3d <unknown>
#8 0x557b4bae5cc3 <unknown>
#9 0x557b4bab10e4 <unknown>
#10 0x557b4bab20ae <unknown>
#11 0x557b4bd74ce1 <unknown>
#12 0x557b4bd78b7e <unknown>
#13 0x557b4bd624b5 <unknown>
#14 0x557b4bd797d6 <unknown>
#15 0x557b4bd45dbf <unknown>
#16 0x557b4bd9c748 <unknown>
#17 0x557b4bd9c917 <unknown>
#18 0x557b4bdad773 <unknown>
#19 0x7fab6a7abea7 start_thread
; 2014)
[2023-11-07 21:36:00,096] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 21:36:00,203] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
