[2023-11-07 21:57:51,498] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag_data.test_selenium manual__2023-11-07T21:57:50.950870+00:00 [queued]>
[2023-11-07 21:57:51,511] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: selenium_dag_data.test_selenium manual__2023-11-07T21:57:50.950870+00:00 [queued]>
[2023-11-07 21:57:51,511] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:57:51,511] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-11-07 21:57:51,511] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-07 21:57:51,530] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test_selenium> on 2023-11-07 21:57:50.950870+00:00
[2023-11-07 21:57:51,538] {standard_task_runner.py:52} INFO - Started process 4753 to run task
[2023-11-07 21:57:51,543] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_dag_data', 'test_selenium', 'manual__2023-11-07T21:57:50.950870+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/test_selinium.py', '--cfg-path', '/tmp/tmpncaqnw83', '--error-file', '/tmp/tmp0wx_26ji']
[2023-11-07 21:57:51,546] {standard_task_runner.py:80} INFO - Job 43: Subtask test_selenium
[2023-11-07 21:57:51,632] {task_command.py:370} INFO - Running <TaskInstance: selenium_dag_data.test_selenium manual__2023-11-07T21:57:50.950870+00:00 [running]> on host ad682aabf7c8
[2023-11-07 21:57:51,739] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=selenium_dag_data
AIRFLOW_CTX_TASK_ID=test_selenium
AIRFLOW_CTX_EXECUTION_DATE=2023-11-07T21:57:50.950870+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-07T21:57:50.950870+00:00
[2023-11-07 21:57:51,740] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-11-07 21:57:52,035] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:57:52,095] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2023-11-07 21:57:52,131] {logger.py:11} INFO - Driver [/root/.wdm/drivers/chromedriver/linux64/119.0.6045.105/chromedriver-linux64/chromedriver] found in cache
[2023-11-07 21:57:57,639] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/dags/test_selinium.py", line 48, in test_selenium_driver
    username_input.send_keys(username)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 230, in send_keys
    self._execute(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=119.0.6045.105)
Stacktrace:
#0 0x558d616b6ce3 <unknown>
#1 0x558d613847ae <unknown>
#2 0x558d613c7a7b <unknown>
#3 0x558d613c7219 <unknown>
#4 0x558d613f6c92 <unknown>
#5 0x558d613c2788 <unknown>
#6 0x558d613f6e1e <unknown>
#7 0x558d6140f288 <unknown>
#8 0x558d613f6a43 <unknown>
#9 0x558d613c0bc6 <unknown>
#10 0x558d613c1fb2 <unknown>
#11 0x558d6168bd67 <unknown>
#12 0x558d6168ee4d <unknown>
#13 0x558d6168e8f8 <unknown>
#14 0x558d6168f365 <unknown>
#15 0x558d6167e19f <unknown>
#16 0x558d6168f6f2 <unknown>
#17 0x558d61668626 <unknown>
#18 0x558d616a7e55 <unknown>
#19 0x558d616a803b <unknown>
#20 0x558d616b626f <unknown>
#21 0x7fec993fdea7 start_thread

[2023-11-07 21:57:57,660] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_dag_data, task_id=test_selenium, execution_date=20231107T215750, start_date=20231107T215751, end_date=20231107T215757
[2023-11-07 21:57:57,679] {standard_task_runner.py:92} ERROR - Failed to execute job 43 for task test_selenium (Message: element not interactable
  (Session info: headless chrome=119.0.6045.105)
Stacktrace:
#0 0x558d616b6ce3 <unknown>
#1 0x558d613847ae <unknown>
#2 0x558d613c7a7b <unknown>
#3 0x558d613c7219 <unknown>
#4 0x558d613f6c92 <unknown>
#5 0x558d613c2788 <unknown>
#6 0x558d613f6e1e <unknown>
#7 0x558d6140f288 <unknown>
#8 0x558d613f6a43 <unknown>
#9 0x558d613c0bc6 <unknown>
#10 0x558d613c1fb2 <unknown>
#11 0x558d6168bd67 <unknown>
#12 0x558d6168ee4d <unknown>
#13 0x558d6168e8f8 <unknown>
#14 0x558d6168f365 <unknown>
#15 0x558d6167e19f <unknown>
#16 0x558d6168f6f2 <unknown>
#17 0x558d61668626 <unknown>
#18 0x558d616a7e55 <unknown>
#19 0x558d616a803b <unknown>
#20 0x558d616b626f <unknown>
#21 0x7fec993fdea7 start_thread
; 4753)
[2023-11-07 21:57:57,694] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-07 21:57:57,737] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
